### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by stevel4857** [delapuente/aframe-sharedspace-component#1]
I tried this on my platform and also on the test link and neither brings up networked avatars. Just wondering if this has been discontinued. This is an amazing component. 
Tried it here:
https://vr-chat.glitch.me/?room-1510150866435
and on my server. Neither seemed to work.

Thanks!

**Comment by delapuente** [comment]
I think it's working. What's your problem?

**Comment by stevel4857** [comment]
It just wasn't working last week. I haven't tried it since then. I have two
machines in my office, one with Oculus and one with Vive. So, it's easy for
me to check networking.
I was just worried when it wasn't working that day. I will check it again
today.

Thanks for following up.

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377

**Comment by aliy321** [comment]
what's the max number of user?

**Comment by delapuente** [comment]
Theoretically, there is no max number but the sharedspace component follows a [full mesh topology](https://en.wikipedia.org/wiki/Network_topology#Fully_connected_network) which does not scale well for a large number of participants. Notice also that, by default, you're using my personal signalling server ([`provider` property](https://github.com/delapuente/aframe-sharedspace-component/tree/master/dist#sharedspace)). Although convenient, you should switch to your own for improved availability

**Comment by ValdoMpinga** [comment]
Hello, does it still works? Im trying to use it, it connects and asks for the microfone permission and all but when i speak on it i cant ear nothing on both devices... and the spheres dont appear, only an empty map

```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://aframe.io/releases/1.0.0/aframe.min.js"></script>
    <script src="https://unpkg.com/aframe-sharedspace-component@1.0.1/dist/aframe-sharedspace-component.min.js"></script>
    <script src="https://unpkg.com/aframe-environment-component@1.3.3/dist/aframe-environment-component.min.js"></script>

    <!-- <script src="./components/testComponent.js"></script> -->
  </head>
  <body>
    <a-scene>
      <a-entity sharedspace="audio: true"  environment="preset: checkerboard" avatars> </a-entity>
    </a-scene>
  </body>
  <template>
    <a-sphere radius="0.1"></a-sphere>
  </template>
</html>
```

the code seems normal, please help with any hints

**Comment by stevel4857** [comment]
Sorry. This code is pretty old. I would search aframe environment component and see if it is available as updated code somewhere. I had a lot of downloads four years ago. I should probably pull this.
